src/Entity/Achat.php
<?php

namespace App\Entity;

use App\Repository\AchatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AchatRepository::class)]
#[ORM\HasLifecycleCallbacks()]
class Achat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateAchat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateLivraison = null;

    #[ORM\Column]
    private ?float $prixTotal = null;

    // #[ORM\ManyToOne(inversedBy: 'achats')]
    // #[ORM\JoinColumn(nullable: false)]
    // private ?Client $client = null;

    #[ORM\ManyToOne(inversedBy: 'achats')]
    #[ORM\JoinColumn(nullable: false)]
    private ?MobileMoney $mobileMoney = null;

    #[ORM\Column(length: 255)]
    private ?string $numeroReference = null;

    #[ORM\Column]
    private ?bool $isApprouve = null;

    #[ORM\Column]
    private ?bool $isAnnule = null;

    #[ORM\Column]
    private ?bool $isEnCours = null;

    #[ORM\Column]
    private ?bool $isPaye = null;

    #[ORM\Column]
    private ?bool $isLivre = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable:true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'achat', targetEntity: LigneAchat::class, orphanRemoval: true, cascade: ["persist"])]
    private Collection $ligneAchats;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\ManyToOne(inversedBy: 'achats')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;  

    public function getCodeClient(){
        if($this->getUser()){
            return $this->getUser()->getCodeClient();
        }else{
            return "Aucun client";
        }
    }
    
    
    #[ORM\PreUpdate]
    public function misAJour(){
        if($this->isApprouve){
            $this->etat="Approuvé";
        }elseif($this->isLivre){
            $this->etat="Livré";   
        }elseif($this->isAnnule){
            $this->etat="Annulé";   
        }
        // dd("testons");
    }

    public function __construct(User $user)
    {
        $this->user=$user;
        $this->dateAchat=new \DateTimeImmutable();
        $this->createdAt=new \DateTimeImmutable();
        // dd("salut");
        $this->ligneAchats = new ArrayCollection();
        $this->isApprouve=false;
        $this->isAnnule=false;
        $this->isEnCours=false;
        $this->isPaye=false;
        $this->isLivre=false;
        $this->email=$this->user->getEmail();
        $this->etat="En attente validation";
    }

    
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->dateAchat;
    }

    public function setDateAchat(\DateTimeInterface $dateAchat): self
    {
        $this->dateAchat = $dateAchat;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->dateLivraison;
    }

    public function setDateLivraison(?\DateTimeInterface $dateLivraison): self
    {
        $this->dateLivraison = $dateLivraison;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prixTotal;
    }

    public function setPrixTotal(float $prixTotal): self
    {
        $this->prixTotal = $prixTotal;

        return $this;
    }

    // public function getClient(): ?Client
    // {
    //     return $this->client;
    // }

    // public function setClient(?Client $client): self
    // {
    //     $this->client = $client;

    //     return $this;
    // }

    public function getMobileMoney(): ?MobileMoney
    {
        return $this->mobileMoney;
    }

    public function setMobileMoney(?MobileMoney $mobileMoney): self
    {
        $this->mobileMoney = $mobileMoney;

        return $this;
    }

    public function getNumeroReference(): ?string
    {
        return $this->numeroReference;
    }

    public function setNumeroReference(string $numeroReference): self
    {
        $this->numeroReference = $numeroReference;

        return $this;
    }

    public function isIsApprouve(): ?bool
    {
        return $this->isApprouve;
    }

    public function setIsApprouve(bool $isApprouve): self
    {
        $this->isApprouve = $isApprouve;

        return $this;
    }

    public function isIsAnnule(): ?bool
    {
        return $this->isAnnule;
    }

    public function setIsAnnule(bool $isAnnule): self
    {
        $this->isAnnule = $isAnnule;

        return $this;
    }

    public function isIsEnCours(): ?bool
    {
        return $this->isEnCours;
    }

    public function setIsEnCours(bool $isEnCours): self
    {
        $this->isEnCours = $isEnCours;

        return $this;
    }

    public function isIsPaye(): ?bool
    {
        return $this->isPaye;
    }

    public function setIsPaye(bool $isPaye): self
    {
        $this->isPaye = $isPaye;

        return $this;
    }

    public function isIsLivre(): ?bool
    {
        return $this->isLivre;
    }

    public function setIsLivre(bool $isLivre): self
    {
        $this->isLivre = $isLivre;

        return $this;
    }

    /**
     * @return Collection<int, LigneAchat>
     */
    public function getLigneAchats(): Collection
    {
        return $this->ligneAchats;
    }

    public function addLigneAchat(LigneAchat $ligneAchat): self
    {
        if (!$this->ligneAchats->contains($ligneAchat)) {
            $this->ligneAchats->add($ligneAchat);
            $ligneAchat->setAchat($this);
        }

        return $this;
    }

    public function removeLigneAchat(LigneAchat $ligneAchat): self
    {
        if ($this->ligneAchats->removeElement($ligneAchat)) {
            // set the owning side to null (unless already changed)
            if ($ligneAchat->getAchat() === $this) {
                $ligneAchat->setAchat(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', null,[
                "disabled"=>true,
            ])
            // ->add('roles')
            ->add('identite', IdentiteType::class)
            ->add('adresse', AdresseType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\ChangePasswordFormType;
use App\Form\UserType;
use App\Repository\ClientRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        // $this->addFlash('success', 'Vous avez créez un compte admin.');
        $this->addFlash(
            'warning',
            'Your changes were saved!'
        );


        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user, ClientRepository $clientRepository): Response
    {
        // $client=$clientRepository->findOneBy(["utilisateur"=>$user]);
        // return $this->redirectToRoute('app_client_show', ["id"=>$client->getId()], Response::HTTP_SEE_OTHER);

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_show', ['id'=> $user->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    
    #[Route('/change/password', name: 'app_user_reset_password', methods: ['GET', 'POST'])]
    public function changePassword(Request $request,UserPasswordHasherInterface $userPasswordHasher, UserRepository $userRepository): Response
    {
        // dd("reset");
        $form = $this->createForm(ChangePasswordFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user=$this->getUser();
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    // $form->get('plainPassword')->getData()
                    $form->get('plainPassword')->getData()
                )
            );

            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_show', ['id'=> $user->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/changePassword.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/changePassword.html.twig
{% extends 'base.html.twig' %}

{% block title %}Changer de mot de passe 
{% endblock %}
{% block ariane %}
	{{parent() }}
	Gestion users
{% endblock %}
{% block lesboutons %}

	<a href="{{path('app_user_index')}}" title="Retour à la liste " class="btn btn-info btn-sm">
		<i class="fa fa-reply-all"></i>
		Rétour
	</a>
{% endblock %}
{% block hero %}{% endblock %}

{% block innerPage %}
	Création d'un compte adminsitrateur
{% endblock %}

{% block body %}
<!-- product section -->

			<div class="row">
				<div class="col col-6">

	{{ form_start(form) }}
	{{ form_row(form.plainPassword) }}
	{# {{ form_row(form.identite) }}
	{{ form_row(form.adresse) }} #}
	<button type="submit" class="btn btn-default btn-primary">
		<span class="fa fa-user">
			Enregistrer
		</button>
		{{ form_end(form) }}

		</div>
		</div>
	{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer profile 
{% endblock %}

{% block body %}
	<!-- product section -->
	{# <div class="my-custom-class-for-errors">
	        {{ form_errors(form) }}
	    </div> #}

	{{ form_start(form) }}

		<div class="row"> 
				<div class="col col-md-6">
		{{ form_row(form.identite.nom) }}
				</div>
				<div class="col col-md-6">
		{{ form_row(form.identite.postnom) }}
				</div>
				<div class="col col-md-6">
		{{ form_row(form.identite.prenom) }}
				</div>
			<div class="col col-md-6">
			{{ form_row(form.email) }}
			</div>
			<div class="col col-md-4">
		{{ form_row(form.adresse.telephone) }}
				</div>
				<div class="col col-md-8">
		{{ form_row(form.adresse.adresse) }}
				</div>
				<div class="col col-md-6">
		{{ form_row(form.adresse.ville) }}
				</div>
				<div class="col col-md-6">
		{{ form_row(form.adresse.pays) }}
				</div>
				
	</div>
<div class="row">
	<div class="col col-md-12">
	<a class="btn btn-primary pull left" href="{{ path('app_user_reset_password') }}">Changer mot de passe</a>

		<button type="submit" class="btn btn-default btn-primary pull-right">
			<span class="fa fa-user">
				Enregistrer
			</button>
		</div>
	</div>
	{{ form_end(form) }}

</div>

</div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs {% endblock %}

{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Identité</th>
                <th>Adresse</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.rolePrincipal }}</td>
                <td>{{ user.identite }}</td>
                <td>{{ user.adresse }}</td>
                <td>
                    <div class="btn-group">
                    <a class="btn btn-sm btn-default" href="{{ path('app_user_show', {'id': user.id}) }}">voir</a>
                    <a  class="btn btn-sm  btn-default" href="{{ path('app_user_edit', {'id': user.id}) }}">modifier</a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('app_register') }}"> Nouvel utilisateur </a>
    <a class="btn btn-success" href="{{ path('app_register_admin') }}"> Nouvel admin </a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile de {{ user.identite }} {% endblock %}

{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ user.email }} </td>
            </tr>
            <tr>
                <th>Rôle principal</th>
                <td>{{ user.rolePrincipal }}</td>
            </tr>
            <tr>
                <th>Code client </th>
                <td>{{ user.codeClient }}</td>
            </tr>

            <tr>
                <th>Noms complets  </th>
                <td>{{ user.identite }}</td>
            </tr>
            <tr>
                <th>Adresse </th>
                <td>{{ user.adresse }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN") %}

    <a class="btn btn-success" href="{{ path('app_user_index') }}">retour à la liste </a>
    {% endif %}

    <a class="btn btn-primary" href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier profile</a>
    <a class="btn btn-primary pull rigth" href="{{ path('app_user_reset_password') }}">Changer mot de passe</a>

    {# {{ include('user/_delete_form.html.twig') }} #}
{% endblock %}